spring.application.name=ecommerce

# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/techlab
spring.datasource.username=postgres
# clave que le pusiste a PostgreSQL
spring.datasource.password=admin

# Estrategia de creación de tablas (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
